<#
.SYNOPSIS
    Builds the Go protocol bridge as a C-ABI DLL.

.DESCRIPTION
    cgo cannot use MSVC, so -buildmode=c-shared needs a GCC-compatible compiler.
    This locates a mingw-w64 gcc (winlibs, MSYS2 or one already on PATH) and
    builds bridge/ into xmbridge.dll plus its generated header.

    The resulting DLL is a plain C-ABI module, so the MSVC-built application
    links against it through the generated import library without caring that
    the other side was compiled by gcc.

.PARAMETER Version
    Stamped into the DLL's version resource and reported by xmb_version, so the
    about box and the file's Windows properties cannot drift apart.

.PARAMETER VersionInfoRc
    Version resource generated by CMake from bridge/versioninfo.rc.in. Compiled
    with windres into a .syso, which is how a Go build gets Windows resources.
    Mandatory rather than optional because an unversioned DLL cannot be signed.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$OutputDir,

    [Parameter(Mandatory = $true)]
    [string]$Version,

    [Parameter(Mandatory = $true)]
    [string]$VersionInfoRc,

    [ValidateSet('release', 'debug')]
    [string]$Configuration = 'release'
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$BridgeDir = Join-Path $RepoRoot 'bridge'

function Find-Tool([string]$Name, [string[]]$Candidates) {
    $onPath = Get-Command $Name -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }
    foreach ($c in $Candidates) {
        if (Test-Path $c) { return $c }
    }
    return $null
}

$go = Find-Tool 'go' @(
    "$env:ProgramFiles\Go\bin\go.exe",
    "$env:LOCALAPPDATA\Programs\Go\bin\go.exe"
)
if (-not $go) {
    throw "Go toolchain not found. Install it with: winget install --id GoLang.Go"
}

$gcc = Find-Tool 'gcc' @(
    "$env:ProgramFiles\WinLibs\mingw64\bin\gcc.exe",
    "$env:LOCALAPPDATA\Microsoft\WinGet\Packages\BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe\mingw64\bin\gcc.exe",
    "C:\msys64\mingw64\bin\gcc.exe",
    "C:\mingw64\bin\gcc.exe"
)
if (-not $gcc) {
    # WinGet installs into a hashed directory; search for it as a last resort.
    $wingetRoot = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages'
    if (Test-Path $wingetRoot) {
        $found = Get-ChildItem $wingetRoot -Recurse -Filter 'gcc.exe' -ErrorAction SilentlyContinue |
                 Select-Object -First 1
        if ($found) { $gcc = $found.FullName }
    }
}
if (-not $gcc) {
    throw "mingw-w64 gcc not found. Install it with: winget install --id BrechtSanders.WinLibs.POSIX.UCRT"
}

# windres ships in the same bin directory as gcc, under either name depending on
# whether the toolchain was built as a cross compiler.
$gccBin = Split-Path -Parent $gcc
$windres = Find-Tool 'windres' @(
    (Join-Path $gccBin 'windres.exe'),
    (Join-Path $gccBin 'x86_64-w64-mingw32-windres.exe')
)
if (-not $windres) {
    throw "windres not found next to $gcc. Reinstall mingw-w64 with its binutils."
}

Write-Host "==> go:      $go"
Write-Host "==> gcc:     $gcc"
Write-Host "==> windres: $windres"

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
$OutputDir = (Resolve-Path $OutputDir).Path
$dllPath = Join-Path $OutputDir 'xmbridge.dll'

# The Go linker takes Windows resources only as a compiled .syso sitting in the
# package directory, so this has to be written into bridge/ rather than into the
# output directory. It is regenerated on every build and gitignored.
if (-not (Test-Path $VersionInfoRc)) {
    throw "version resource not found at $VersionInfoRc. Configure with CMake first."
}

$syso = Join-Path $BridgeDir 'versioninfo.syso'
Write-Host "==> windres $VersionInfoRc"
& $windres --input $VersionInfoRc --output $syso --output-format coff --target pe-x86-64
if ($LASTEXITCODE -ne 0) { throw "windres failed on $VersionInfoRc" }

# Put gcc on PATH for the duration of the build so cgo can find the whole
# toolchain (gcc drives ld, as and the runtime libs from the same bin dir).
$env:PATH = "$gccBin;$env:PATH"
$env:CGO_ENABLED = '1'
$env:CC = $gcc
$env:GOOS = 'windows'
$env:GOARCH = 'amd64'

# -X keeps the reported version in step with the project version without a
# generated Go file: a debug build strips nothing, but still has to be stamped.
$ldflags = "-X main.Version=$Version"
if ($Configuration -ne 'debug') { $ldflags = "-s -w $ldflags" }

Push-Location $BridgeDir
try {
    Write-Host "==> go mod tidy"
    & $go mod tidy
    if ($LASTEXITCODE -ne 0) { throw "go mod tidy failed" }

    Write-Host "==> go build -buildmode=c-shared ($Version)"
    $buildArgs = @('build', '-buildmode=c-shared', '-trimpath', '-ldflags', $ldflags,
                   '-o', $dllPath, '.')

    & $go @buildArgs
    if ($LASTEXITCODE -ne 0) { throw "go build failed" }
} finally {
    Pop-Location
}

if (-not (Test-Path $dllPath)) {
    throw "expected $dllPath to exist after build"
}

Write-Host "==> built $dllPath"
